In [2]:
import pandas as pd

In [3]:
fn='data.chadwyck_rhyme.pkl'
df = pd.read_pickle(fn)
# df5=pd.read_pickle(fn)
# df5

In [4]:
d=dict(df.ybin.value_counts().sort_index())

In [5]:
print('; '.join(f'{k[3:]} (n={v:,})' for k,v in d.items()))

1600-1650 (n=5,549); 1600-1700 (n=2,361); 1650-1700 (n=6,632); 1700-1750 (n=8,076); 1700-1800 (n=3,960); 1750-1800 (n=8,155); 1800-1850 (n=4,971); 1800-1900 (n=4,707); 1850-1900 (n=4,752); 1900-1950 (n=4,145); 1900-2000 (n=4,561); 1950-2000 (n=1,819)

In [12]:
df2 = pd.read_pickle('data.allpoems.pkl')

excl_prompts=[
    'Write an unryhmed poem in the style of Shakespeare\'s dramatic monologues.',
    'Write a poem in the style of Shakespeare\'s dramatic monologues.',
    'Write a poem in the style of e.e. cummings',
    # 'Write a poem in the style of Walt Whitman.',
    'Write a poem in the style of Wallace Stevens.',
    'Continue the following poem:\n\nTyping, typing, fingers on the keyboard\nThe keys crack and bend under sweat and weight,\n'
]

df2 = df2[~df2.prompt.isin(excl_prompts)]
df2.groupby('prompt_type').prompt.value_counts()

prompt_type   prompt
DO_rhyme      Write a poem in heroic couplets.                               376
              Write a poem (with 20+ lines) that rhymes.                     372
              Write a long poem that does rhyme.                             370
              Write a poem in the style of Emily Dickinson.                  369
              Write a poem that does rhyme.                                  369
              Write a poem in ballad stanzas.                                348
              Write an rhyming poem.                                         334
              Write a short poem that does rhyme.                            263
              Write an ryhmed poem in the style of Shakespeare's sonnets.    257
MAYBE_rhyme   Write a long poem.                                             425
              Write a poem (with 20+ lines).                                 396
              Write a poem.                                                  390
              Write a poem in groups of two lines.                           383
              Write a poem in stanzas of 4 lines each.                       345
              Write a short poem.                                            233
do_NOT_rhyme  Write a poem (with 20+ lines) that does NOT rhyme.             382
              Write a long poem that does NOT rhyme.                         365
              Write a poem in the style of Walt Whitman.                     350
              Write a poem in free verse.                                    322
              Write a poem in blank verse.                                   315
              Write a poem that does NOT rhyme.                              307
              Write an unrhymed poem.                                        305
              Write a short poem that does NOT rhyme.                        242
Name: count, dtype: int64

In [20]:
row = df2[df2['model'] == 'b. 1950-2000'].sample(n=1).iloc[0]
print(row.poem)
print(row.perc_rhyming_lines)

An incomplete moon broke through branches
kneading me into shadows on the window
The sun died in my dream last night
Fog rose from moldy benches
I touched your shoulder, said I'm sorry
Even cats are afraid of loneliness

Forty-one days of rain
You mumbled it was time
to make a boat
When I turned my head
you started dancing "Fernando's" tango
waving a read scarf on the balcony
I passed a man peeing between buildings
frightened by the echoes of my own footsteps

When the rain stopped
Tompkin Square Park residents climbed out
to mend their plastic tents with clothes pins
and sweep their ratty carpets within fences
I walked towards the Manhattan Bridge
to see the Chinese bag lady
behind her lace curtain
33.33333333333333

In [11]:
df2.query('prompt_type == "do_NOT_rhyme"').groupby(['prompt']).perc_rhyming_lines.median().sort_values()

prompt
Write a poem (with 20+ lines) that does NOT rhyme.     9.375000
Write a poem in free verse.                           11.111111
Write a long poem that does NOT rhyme.                12.500000
Write a poem in the style of Walt Whitman.            13.563218
Write a poem in blank verse.                          14.285714
Write an unrhymed poem.                               14.285714
Write a poem that does NOT rhyme.                     15.000000
Write a short poem that does NOT rhyme.               16.666667
Name: perc_rhyming_lines, dtype: float64

In [10]:
df2.groupby(['prompt_type','model']).perc_rhyming_lines.median()

prompt_type   model
DO_rhyme      claude-3-haiku-20240307     25.000000
              claude-3-opus-20240229      20.000000
              claude-3-sonnet-20240229    15.000000
              gemini-pro                  20.416667
              gpt-3.5-turbo               20.000000
              gpt-4-turbo                 19.444444
              llama2-uncensored:7b        20.714286
Human         b. 1600-1650                40.000000
              b. 1650-1700                34.090909
              b. 1700-1750                29.166667
              b. 1750-1800                25.000000
              b. 1800-1850                25.806452
              b. 1850-1900                23.809524
              b. 1900-1950                14.285714
              b. 1950-2000                11.111111
MAYBE_rhyme   claude-3-haiku-20240307     16.666667
              claude-3-opus-20240229      18.750000
              claude-3-sonnet-20240229    20.000000
              gemini-pro                  20.000000
              gpt-3.5-turbo               18.750000
              gpt-4-turbo                 16.666667
              llama2-uncensored:7b        15.000000
do_NOT_rhyme  claude-3-haiku-20240307     13.194444
              claude-3-opus-20240229       8.333333
              claude-3-sonnet-20240229    12.500000
              gemini-pro                  16.666667
              gpt-3.5-turbo               10.000000
              gpt-4-turbo                  6.666667
              llama2-uncensored:7b        18.465909
Name: perc_rhyming_lines, dtype: float64

,count,mean,std,min,25%,50%,75%,max
prompt_type,,,,,,,,
DO_rhyme,3058.0,22.395827,16.434365,0.0,12.500000,20.000000,28.571429,100.0
Human,59688.0,33.784601,26.824997,0.0,12.727273,25.000000,50.000000,100.0
MAYBE_rhyme,2172.0,19.586643,13.731919,0.0,11.111111,17.857143,25.000000,100.0
do_NOT_rhyme,2588.0,14.467616,12.548274,0.0,5.715812,12.500000,20.833333,90.0

In [40]:
for g,gdf in df2.groupby('prompt_type'):
    prompt_counts = gdf.prompt.value_counts()
    prompts = prompt_counts.index
    if len(prompts)>1:  
        print(g)
        print('; '.join(f'"{p.strip()[:-1]}" (n={prompt_counts[p]:,})' for p in prompts))
        print()

DO_rhyme
"Write a poem in heroic couplets" (n=376); "Write a poem (with 20+ lines) that rhymes" (n=372); "Write a long poem that does rhyme" (n=370); "Write a poem that does rhyme" (n=369); "Write a poem in the style of Emily Dickinson" (n=369); "Write a poem in ballad stanzas" (n=348); "Write an rhyming poem" (n=334); "Write a short poem that does rhyme" (n=263); "Write an ryhmed poem in the style of Shakespeare's sonnets" (n=257)

MAYBE_rhyme
"Write a long poem" (n=425); "Write a poem (with 20+ lines)" (n=396); "Write a poem" (n=390); "Write a poem in groups of two lines" (n=383); "Write a poem in stanzas of 4 lines each" (n=345); "Write a short poem" (n=233)

do_NOT_rhyme
"Write a poem (with 20+ lines) that does NOT rhyme" (n=382); "Write a long poem that does NOT rhyme" (n=365); "Write a poem in the style of Walt Whitman" (n=350); "Write a poem in free verse" (n=322); "Write a poem in blank verse" (n=315); "Write a poem that does NOT rhyme" (n=307); "Write an unrhymed poem" (n=305); "Write a short poem that does NOT rhyme" (n=242)

In [48]:
df2.prompt_type.value_counts()

prompt_type
Human           59688
DO_rhyme         3058
do_NOT_rhyme     2588
MAYBE_rhyme      2172
Name: count, dtype: int64

In [53]:
dfmeta=pd.read_csv('/Users/ryan/lltk_data/corpora/chadwyck_poetry/metadata.csv')

/var/folders/py/jyzw5nyj1fnf0c_1czgsg2fc0000gn/T/ipykernel_37215/3394522058.py:1: DtypeWarning: Columns (12,15,25,31,33,37,40,45,46,49,51,56,57,59,60,69,72,73,78,84,86,95,97,99) have mixed types. Specify dtype option on import or set low_memory=False.
  dfmeta=pd.read_csv('/Users/ryan/lltk_data/corpora/chadwyck_poetry/metadata.csv')

In [54]:
len(df2[df2.prompt_type=='Human'])

59688

In [68]:
# dict(df2.iloc[-1])
d2=dict(df2.attdbase.value_counts())
print('; '.join(f'{k} (n={v:,})' for k,v in d2.items()))

English Poetry (n=36,066); Twentieth-Century American Poetry (n=6,571); American Poetry (n=5,854); English Poetry 2nd Edition (n=4,409); Twentieth-Century English Poetry (n=3,540); Modern Poetry (n=1,467); Twentieth-Century African-American Poetry (n=699); The Faber Poetry Library (n=680); African-American Poetry (n=402)

In [43]:
dfhuman = df2[df2.prompt_type=='Human']

In [93]:
dfhuman[df.ybin.str.contains('50')].groupby('ybin').perc_rhyming_lines.describe()

,count,mean,std,min,25%,50%,75%,max
ybin,,,,,,,,
b. 1600-1650,5549.0,44.300076,28.425351,0.0,18.750000,40.000000,71.428571,100.000000
b. 1650-1700,6632.0,41.977256,27.630429,0.0,18.750000,34.000000,66.666667,100.000000
b. 1700-1750,8076.0,37.327037,26.488896,0.0,16.666667,29.166667,50.000000,100.000000
b. 1750-1800,8155.0,35.075270,26.699908,0.0,14.814815,25.000000,50.000000,100.000000
b. 1800-1850,4971.0,35.499066,27.115740,0.0,13.888889,25.925926,52.704678,100.000000
b. 1850-1900,4752.0,29.827907,24.236842,0.0,12.500000,23.529412,42.857143,100.000000
b. 1900-1950,4145.0,18.713900,18.024599,0.0,4.000000,14.285714,27.272727,100.000000
b. 1950-2000,1819.0,15.290000,16.118483,0.0,0.000000,11.428571,22.580645,87.804878

In [69]:
dfhuman

,model,temp,prompt,poem,num_lines,num_rhyming_lines,perc_rhyming_lines,prompt_type,_id,_corpus,...,prologue,sub,cell,target,bo,bnote,video,pndfig,ybin,path_txt
0,b. 1800-1850,NaN,NaN,"Look at butterfly Lil,\n ...",48,19,39.583333,Human,_chadwyck_poetry/english/wardfred/Z300519494,chadwyck_poetry,...,,,,,,,,,b. 1800-1850,/Users/ryan/lltk_data/corpora/chadwyck_poetry/...
1,b. 1900-1950,NaN,NaN,"Thirty yards apart, they face\nnot each other\...",17,9,52.941176,Human,_chadwyck_poetry/c20-american/am22114/Z300241936,chadwyck_poetry,...,,,,,,,,,b. 1900-2000,/Users/ryan/lltk_data/corpora/chadwyck_poetry/...
2,b. 1650-1700,NaN,NaN,"The Cautious Heathens, ere they would admit\nT...",53,18,33.962264,Human,_chadwyck_poetry/english/heyrickt/Z300394801,chadwyck_poetry,...,,,,,,,,,b. 1650-1700,/Users/ryan/lltk_data/corpora/chadwyck_poetry/...
3,b. 1700-1750,NaN,NaN,"Jesus, in whom the Godhead's rays\n Beam fo...",24,5,20.833333,Human,_chadwyck_poetry/english/wesleych/Z400524691,chadwyck_poetry,...,,,,,,,,,b. 1700-1750,/Users/ryan/lltk_data/corpora/chadwyck_poetry/...
4,b. 1800-1850,NaN,NaN,"Little Master's, hat in hand,\nLet me in your ...",20,2,10.000000,Human,_chadwyck_poetry/american/am0481/Z200161973,chadwyck_poetry,...,,,,,,,,,b. 1800-1850,/Users/ryan/lltk_data/corpora/chadwyck_poetry/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67310,b. 1900-1950,NaN,NaN,"Talk in your sleep of Lilith,\nAnd say that sh...",20,4,20.000000,Human,_chadwyck_poetry/c20-american/am22005/Z200229304,chadwyck_poetry,...,,,,,,,,,b. 1900-1950,/Users/ryan/lltk_data/corpora/chadwyck_poetry/...
67312,b. 1900-1950,NaN,NaN,"Two days of mossy mists,\nsoft & clinging. The...",29,0,0.000000,Human,_chadwyck_poetry/c20-american/am30222/Z300569730,chadwyck_poetry,...,,,,,,,,,b. 1900-2000,/Users/ryan/lltk_data/corpora/chadwyck_poetry/...
67313,b. 1750-1800,NaN,NaN,"O! Molly Bawn, why leave me pining,\n All l...",18,8,44.444444,Human,_chadwyck_poetry/english/loversam/Z300418252,chadwyck_poetry,...,,,,,,,,,b. 1750-1800,/Users/ryan/lltk_data/corpora/chadwyck_poetry/...
67315,b. 1650-1700,NaN,NaN,"Love put his bow into my hand,\n Charg'...",18,5,27.777778,Human,_chadwyck_poetry/english/crompton/Z200325110,chadwyck_poetry,...,,,,,,,,,b. 1650-1700,/Users/ryan/lltk_data/corpora/chadwyck_poetry/...
67316,b. 1650-1700,NaN,NaN,"Vertue's a Babe, first born in Paradise,\nAnd ...",22,14,63.636364,Human,_chadwyck_poetry/american/am1031/Z200182640,chadwyck_poetry,...,,,,,,,,,b. 1650-1700,/Users/ryan/lltk_data/corpora/chadwyck_poetry/...

In [79]:
df2[df2['num_rhyming_lines']==0].groupby('ybin').size() / df2.groupby('ybin').size()

ybin
b. 1600-1650    0.018201
b. 1600-1700    0.017789
b. 1650-1700    0.025483
b. 1700-1750    0.023279
b. 1700-1800    0.027273
b. 1750-1800    0.030656
b. 1800-1850    0.033394
b. 1800-1900    0.051200
b. 1850-1900    0.090488
b. 1900-1950    0.233052
b. 1900-2000    0.266827
b. 1950-2000    0.280924
dtype: float64

In [80]:
df2['perc_rhyming_lines'].describe()

count    67506.000000
mean        32.071313
std         26.159222
min          0.000000
25%         12.500000
50%         25.000000
75%         48.230042
max        100.000000
Name: perc_rhyming_lines, dtype: float64

In [84]:
df[df2['perc_rhyming_lines']>=50].groupby('ybin').size() / df2.groupby('ybin').size()

ybin
b. 1600-1650    0.449991
b. 1600-1700    0.415925
b. 1650-1700    0.389324
b. 1700-1750    0.311664
b. 1700-1800    0.278283
b. 1750-1800    0.264868
b. 1800-1850    0.290284
b. 1800-1900    0.273210
b. 1850-1900    0.223906
b. 1900-1950    0.074065
b. 1900-2000    0.070818
b. 1950-2000    0.052776
dtype: float64

In [91]:
dfnonhuman = df2[df2.prompt_type=='do_NOT_rhyme']
len(dfnonhuman[dfnonhuman['perc_rhyming_lines']>=50]) / len(dfnonhuman)

0.02357032457496136

In [102]:
df3 = df2[(df2.prompt_type!='Human') | (df2.ybin=='b. 1950-2000')]
df3.groupby('prompt_type').perc_rhyming_lines.describe()

,count,mean,std,min,25%,50%,75%,max
prompt_type,,,,,,,,
DO_rhyme,3058.0,22.395827,16.434365,0.0,12.500000,20.000000,28.571429,100.000000
Human,1819.0,15.290000,16.118483,0.0,0.000000,11.428571,22.580645,87.804878
MAYBE_rhyme,2172.0,19.586643,13.731919,0.0,11.111111,17.857143,25.000000,100.000000
do_NOT_rhyme,2588.0,14.467616,12.548274,0.0,5.715812,12.500000,20.833333,90.000000

In [114]:
df2['prompt_type2'] = [x if x!='Human' else y for x,y in zip(df2.prompt_type,df2.ybin)]
df2[~df2.prompt_type2.str.contains('50')].groupby(['prompt_type2']).perc_rhyming_lines.describe().sort_values('50%')

,count,mean,std,min,25%,50%,75%,max
prompt_type2,,,,,,,,
do_NOT_rhyme,2588.0,14.467616,12.548274,0.0,5.715812,12.500000,20.833333,90.0
b. 1900-2000,4561.0,17.470877,17.875306,0.0,0.000000,13.333333,25.000000,100.0
MAYBE_rhyme,2172.0,19.586643,13.731919,0.0,11.111111,17.857143,25.000000,100.0
DO_rhyme,3058.0,22.395827,16.434365,0.0,12.500000,20.000000,28.571429,100.0
b. 1800-1900,4707.0,33.993507,26.705190,0.0,13.333333,25.000000,50.000000,100.0
b. 1700-1800,3960.0,35.483693,26.504917,0.0,15.290033,25.857143,50.000000,100.0
b. 1600-1700,2361.0,42.791937,27.801624,0.0,18.000000,37.500000,68.750000,100.0

In [113]:
(df2.groupby('prompt_type2').num_rhyming_lines.sum() / df2.groupby('prompt_type2').num_lines.sum() * 100).sort_values()

prompt_type2
do_NOT_rhyme    13.275378
b. 1950-2000    16.201475
MAYBE_rhyme     17.255125
b. 1900-2000    18.179225
b. 1900-1950    19.265514
DO_rhyme        19.430367
b. 1850-1900    25.887497
b. 1800-1850    28.678541
b. 1800-1900    28.766200
b. 1750-1800    29.349176
b. 1700-1800    30.148476
b. 1700-1750    32.405758
b. 1600-1700    38.684715
b. 1650-1700    39.372285
b. 1600-1650    40.117957
dtype: float64